DATA SEGMENT
X DW 1221H
TEMP DW 0H
MES DB 10,13,'THE WORD IS NIBBLEWISE PALINDROME $'
MES1 DB 10,13,'THE WORD IS NOT NIBBLEWISE PALINDROME $'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
MOV DS,AX
MOV AX,X
MOV BX,X
MOV CL,04
AND AX,0000FH
AND BX,0F000H
ROL BX,CL
CMP AX,BX
JNZ TER
MOV AX,X
ROR AX,CL
MOV BX,AX
AND AX,000FH
ROR BX,CL
AND BX,000FH
CMP AX,BX
JNZ TER
MOV AH,09H
LEA DX,MES
INT 21H
JMP LAST
TER:MOV AH,09H
LEA DX,MES1
INT 21H
LAST:MOV AH,4CH
INT 21H
CODE ENDS
END START